stages:
  - plot

install:
    stage: plot
    image: "python:3.7"
    script:
        - python setup.py develop
        - pytest
        # - pip install pytest
        # - pytest --verbose
    artifacts:
        paths:
          - plots/
        expire_in: 2 days




